### ISSUE TITLE
CentOS only finds munin

### ISSUE THREAD

**Issue by berkes** [mhwest13/Memcached-Munin-Plugin#1]

**Comment by mhwest13** [comment]
CentOS by default doesn't have Munin in its Repos, you need to either install the EPEL Repo: http://fedoraproject.org/wiki/EPEL (I believe munin is v1.4.x here) or you can install the RPMForge Repo (although munin is v1.2.5 in this repo)

Once you've got these Repo's installed you should be able to yum install munin-node ... Another place you can get the src rpm which EPEL is built on is available here: http://www.rpmfind.net/linux/rpm2html/search.php?query=munin-node

Hope this help, because you didn't give me much to go on with your Issue ;)

**Comment by berkes** [comment]
weird, somehow the githubs ate the body of my issue. Let me repeat it here: 

I already have munin running on centos, 
Now I want to add this munin plugin for our three memcached-servers. I had success with http://exchange.munin-monitoring.org/plugins/memcached_hits_/details, which does not take any configuration, but pulls ip+port from the symlink-name. 

However, Memcached-Munin-Plugin was not working, so it seems. At least, the munin-node-configure --suggest does not report memcached_ at all, and the memcached_multi_ without any "yes (bytes commands conns evictions items memory)" hints. Symlinking it by hand and restarting the -node works, but the logs report several errors:

>  Plugin timeout: memcached_rates : Interrupted system call  (pid 16001)

Which makes me believe it tries to connect to a none-existing ip:port or so. 
My Perl is too poor to debug this in depth, and running the command by hand (perl /etc/munin/plugins/memcached_rates) gives me little to go at, other then an error that some munin.pm could not be found.

**Comment by mhwest13** [comment]
Ok, I guess maybe we should start with some background information so I can better understand what you are monitoring.

What version of Memcached?
What version of Munin?
Which version of Memcached Munin Plugin you are using:
       memcached_ or memcached_multi_ ??

Are you running this plugin on the localhost that is running memcached? If so can you issue the following command and get results.
echo stats | nc localhost 11211 ??

Thanks,

**Comment by laudaksg** [comment]
Can I use this plugin to monitor multiple memcached servers on one machine? I have one for app sessions and one for app data.

**Comment by mhwest13** [comment]
No, I've not written the plugin to have the support to monitor two memcached instances on the same machine. If you have any perl knowledge / knowhow though, you are more than welcome to take a stab at it...
